/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Usuario
 */
public class Principal extends javax.swing.JFrame {

    

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPestañas = new javax.swing.JPanel();
        jlbDesple = new javax.swing.JLabel();
        Pantalla = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jpBotones1 = new javax.swing.JPanel();
        btnclientes1 = new javax.swing.JButton();
        btnEmpleadoP1 = new javax.swing.JButton();
        btnServicio1 = new javax.swing.JButton();
        btnVehiculos1 = new javax.swing.JButton();
        btnProductos1 = new javax.swing.JButton();
        btnCategorias1 = new javax.swing.JButton();
        btnLocalidad1 = new javax.swing.JButton();
        btndetalle1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jpPestañas.setBackground(new java.awt.Color(253, 255, 252));
        jpPestañas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jpPestañas.setForeground(new java.awt.Color(253, 255, 252));

        jlbDesple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/icons8_Menu_32px_1.png"))); // NOI18N

        javax.swing.GroupLayout jpPestañasLayout = new javax.swing.GroupLayout(jpPestañas);
        jpPestañas.setLayout(jpPestañasLayout);
        jpPestañasLayout.setHorizontalGroup(
            jpPestañasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPestañasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbDesple)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPestañasLayout.setVerticalGroup(
            jpPestañasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPestañasLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jlbDesple))
        );

        javax.swing.GroupLayout PantallaLayout = new javax.swing.GroupLayout(Pantalla);
        Pantalla.setLayout(PantallaLayout);
        PantallaLayout.setHorizontalGroup(
            PantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );
        PantallaLayout.setVerticalGroup(
            PantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jpBotones1.setBackground(new java.awt.Color(255, 159, 28));
        jpBotones1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));

        btnclientes1.setBackground(new java.awt.Color(255, 159, 28));
        btnclientes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/user_thin_icon_171437.png"))); // NOI18N
        btnclientes1.setToolTipText("Ingreso Clientes ");
        btnclientes1.setBorderPainted(false);
        btnclientes1.setFocusPainted(false);

        btnEmpleadoP1.setBackground(new java.awt.Color(255, 159, 28));
        btnEmpleadoP1.setForeground(new java.awt.Color(255, 159, 28));
        btnEmpleadoP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/identification_card_thin_icon_171705.png"))); // NOI18N
        btnEmpleadoP1.setToolTipText("Ingreso Empleados");
        btnEmpleadoP1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.orange, new java.awt.Color(51, 204, 255)));
        btnEmpleadoP1.setBorderPainted(false);

        btnServicio1.setBackground(new java.awt.Color(255, 159, 28));
        btnServicio1.setForeground(new java.awt.Color(255, 159, 28));
        btnServicio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/clipboard_text_thin_icon_171881.png"))); // NOI18N
        btnServicio1.setToolTipText("Ingreso Nuevo Servicio");
        btnServicio1.setBorderPainted(false);

        btnVehiculos1.setBackground(new java.awt.Color(255, 159, 28));
        btnVehiculos1.setForeground(new java.awt.Color(255, 159, 28));
        btnVehiculos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/truck_thin_icon_171451.png"))); // NOI18N
        btnVehiculos1.setToolTipText("Ingreso Vehiculo");
        btnVehiculos1.setBorderPainted(false);

        btnProductos1.setBackground(new java.awt.Color(255, 159, 28));
        btnProductos1.setForeground(new java.awt.Color(255, 159, 28));
        btnProductos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/package_thin_icon_171607.png"))); // NOI18N
        btnProductos1.setToolTipText("Ingreso Producto");
        btnProductos1.setBorderPainted(false);

        btnCategorias1.setBackground(new java.awt.Color(255, 159, 28));
        btnCategorias1.setForeground(new java.awt.Color(255, 159, 28));
        btnCategorias1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/list_numbers_thin_icon_171683.png"))); // NOI18N
        btnCategorias1.setToolTipText("Categorias de Productos");
        btnCategorias1.setBorderPainted(false);

        btnLocalidad1.setBackground(new java.awt.Color(255, 159, 28));
        btnLocalidad1.setForeground(new java.awt.Color(255, 159, 28));
        btnLocalidad1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/map_pin_line_thin_icon_171669.png"))); // NOI18N
        btnLocalidad1.setToolTipText("Localidades Destinos");
        btnLocalidad1.setBorderPainted(false);

        btndetalle1.setBackground(new java.awt.Color(255, 159, 28));
        btndetalle1.setForeground(new java.awt.Color(255, 159, 28));
        btndetalle1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/note_pen_thin_icon_171643.png"))); // NOI18N
        btndetalle1.setToolTipText("Ingreso Detalle de Nuevo Servicio");
        btndetalle1.setBorderPainted(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Clientes");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Empleados");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Servicios");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Detalles");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Vehiculos");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Productos");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Categorias");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Localidades");

        javax.swing.GroupLayout jpBotones1Layout = new javax.swing.GroupLayout(jpBotones1);
        jpBotones1.setLayout(jpBotones1Layout);
        jpBotones1Layout.setHorizontalGroup(
            jpBotones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotones1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnclientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpBotones1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(15, 15, 15)
                .addComponent(btnEmpleadoP1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpBotones1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addGap(10, 10, 10)
                .addComponent(btnServicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpBotones1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel4)
                .addGap(15, 15, 15)
                .addComponent(btndetalle1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpBotones1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addGap(15, 15, 15)
                .addComponent(btnVehiculos1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpBotones1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addGap(15, 15, 15)
                .addComponent(btnProductos1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpBotones1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addGap(15, 15, 15)
                .addComponent(btnCategorias1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpBotones1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel8)
                .addGap(15, 15, 15)
                .addComponent(btnLocalidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpBotones1Layout.setVerticalGroup(
            jpBotones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotones1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jpBotones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpBotones1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnclientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jpBotones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpBotones1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEmpleadoP1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jpBotones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpBotones1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnServicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jpBotones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpBotones1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btndetalle1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jpBotones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpBotones1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnVehiculos1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jpBotones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProductos1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jpBotones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpBotones1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnCategorias1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(jpBotones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpBotones1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btnLocalidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jpBotones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBotones1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Pantalla))
            .addComponent(jpPestañas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpPestañas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pantalla)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
           
    public JButton getBtndetalle() {
        return btndetalle1;
    }
    
    public JPanel getJpBotones1() {
        return jpBotones1;
    }

    public void setJpBotones1(JPanel jpBotones1) {
        this.jpBotones1 = jpBotones1;
    }

    public void setBtndetalle(JButton btndetalle) {
        this.btndetalle1 = btndetalle;
    }

    public JButton getBtnCategorias() {
        return btnCategorias1;
    }

    public void setBtnCategorias(JButton btnCategorias) {
        this.btnCategorias1 = btnCategorias;
    }

    public JButton getBtnLocalidad() {
        return btnLocalidad1;
    }

    public void setBtnLocalidad(JButton btnLocalidad) {
        this.btnLocalidad1 = btnLocalidad;
    }

    public JButton getBtnProductos() {
        return btnProductos1;
    }

    public void setBtnProductos(JButton btnProductos) {
        this.btnProductos1 = btnProductos;
    }

    public JButton getBtnVehiculos() {
        return btnVehiculos1;
    }

    public void setBtnVehiculos(JButton btnVehiculos) {
        this.btnVehiculos1 = btnVehiculos;
    }

    public JDesktopPane getPantalla() {
        return Pantalla;
    }

    public void setPantalla(JDesktopPane Pantalla) {
        this.Pantalla = Pantalla;
    }

    public JButton getBtnServicio() {
        return btnServicio1;
    }

    public void setBtnServicio(JButton btnServicio) {
        this.btnServicio1 = btnServicio;
    }

    public JButton getBtnEmpleadoP() {
        return btnEmpleadoP1;
    }
 
    public JLabel getJlbDesple() {
        return jlbDesple;
    }

    public void setJlbDesple(JLabel jlbDesple) {
        this.jlbDesple = jlbDesple;
    }

    public void setBtnEmpleadoP(JButton btnEmpleadoP) {
        this.btnEmpleadoP1 = btnEmpleadoP;
    }

    public JButton getBtnclientes() {
        return btnclientes1;
    }

    public void setBtnclientes(JButton btnclientes) {
        this.btnclientes1 = btnclientes;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Pantalla;
    private javax.swing.JButton btnCategorias1;
    private javax.swing.JButton btnEmpleadoP1;
    private javax.swing.JButton btnLocalidad1;
    private javax.swing.JButton btnProductos1;
    private javax.swing.JButton btnServicio1;
    private javax.swing.JButton btnVehiculos1;
    private javax.swing.JButton btnclientes1;
    private javax.swing.JButton btndetalle1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlbDesple;
    private javax.swing.JPanel jpBotones1;
    private javax.swing.JPanel jpPestañas;
    // End of variables declaration//GEN-END:variables

}
