/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class Vista_Localidad extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vista_Localidad
     */
    public Vista_Localidad() {
        initComponents();
    }

    public JTable getTblLocalidad() {
        return TblLocalidad;
    }

    public void setTblLocalidad(JTable TblLocalidad) {
        this.TblLocalidad = TblLocalidad;
    }

    public JButton getBntModificarL1() {
        return bntModificarL1;
    }

    public void setBntModificarL1(JButton bntModificarL1) {
        this.bntModificarL1 = bntModificarL1;
    }

    public JButton getBtnAgregarL1() {
        return btnAgregarL1;
    }

    public void setBtnAgregarL1(JButton btnAgregarL1) {
        this.btnAgregarL1 = btnAgregarL1;
    }

    public JButton getBtnBuscarL1() {
        return btnBuscarL1;
    }

    public void setBtnBuscarL1(JButton btnBuscarL1) {
        this.btnBuscarL1 = btnBuscarL1;
    }

    public JButton getBtnCancelarL2() {
        return btnCancelarL2;
    }

    public void setBtnCancelarL2(JButton btnCancelarL2) {
        this.btnCancelarL2 = btnCancelarL2;
    }

    public JButton getBtnEliminarL1() {
        return btnEliminarL1;
    }

    public void setBtnEliminarL1(JButton btnEliminarV1) {
        this.btnEliminarL1 = btnEliminarV1;
    }

    public JButton getBtnGuardarL2() {
        return btnGuardarL2;
    }

    public void setBtnGuardarL2(JButton btnGuardarL2) {
        this.btnGuardarL2 = btnGuardarL2;
    }

    public JButton getBtnSalirL1() {
        return btnSalirL1;
    }

    public void setBtnSalirL1(JButton btnSalirL1) {
        this.btnSalirL1 = btnSalirL1;
    }

    public JDialog getDlgLocalidad() {
        return dlgLocalidad;
    }

    public void setDlgLocalidad(JDialog dlgLocalidad) {
        this.dlgLocalidad = dlgLocalidad;
    }

    public JTextField getTxtBusquedaL1() {
        return txtBusquedaL1;
    }

    public void setTxtBusquedaL1(JTextField txtBusquedaL1) {
        this.txtBusquedaL1 = txtBusquedaL1;
    }

    public JTextField getTxtCanton() {
        return txtCanton;
    }

    public void setTxtCanton(JTextField txtCanton) {
        this.txtCanton = txtCanton;
    }

    public JTextField getTxtCodLocal() {
        return txtCodLocal;
    }

    public void setTxtCodLocal(JTextField txtCodLocal) {
        this.txtCodLocal = txtCodLocal;
    }

    public JTextField getTxtPais() {
        return txtPais;
    }

    public void setTxtPais(JTextField txtPais) {
        this.txtPais = txtPais;
    }

    public JTextField getTxtProvincia() {
        return txtProvincia;
    }

    public void setTxtProvincia(JTextField txtProvincia) {
        this.txtProvincia = txtProvincia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgLocalidad = new javax.swing.JDialog();
        lblL2 = new javax.swing.JLabel();
        txtProvincia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCanton = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPais = new javax.swing.JTextField();
        txtCodLocal = new javax.swing.JTextField();
        btnGuardarL2 = new javax.swing.JButton();
        btnCancelarL2 = new javax.swing.JButton();
        ScrlL1 = new javax.swing.JScrollPane();
        TblLocalidad = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtBusquedaL1 = new javax.swing.JTextField();
        btnAgregarL1 = new javax.swing.JButton();
        bntModificarL1 = new javax.swing.JButton();
        btnEliminarL1 = new javax.swing.JButton();
        lblL1 = new java.awt.Label();
        btnSalirL1 = new javax.swing.JButton();
        btnBuscarL1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        lblL2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblL2.setText("Nueva  Localidad");

        txtProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProvinciaActionPerformed(evt);
            }
        });

        jLabel2.setText("ID");

        jLabel3.setText("Provincia");

        jLabel4.setText("Canton");

        jLabel1.setText("Pais");

        btnGuardarL2.setText("Guardar");

        btnCancelarL2.setText("Cancelar");

        javax.swing.GroupLayout dlgLocalidadLayout = new javax.swing.GroupLayout(dlgLocalidad.getContentPane());
        dlgLocalidad.getContentPane().setLayout(dlgLocalidadLayout);
        dlgLocalidadLayout.setHorizontalGroup(
            dlgLocalidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgLocalidadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgLocalidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dlgLocalidadLayout.createSequentialGroup()
                        .addComponent(btnCancelarL2)
                        .addGap(34, 34, 34)
                        .addComponent(btnGuardarL2))
                    .addGroup(dlgLocalidadLayout.createSequentialGroup()
                        .addGroup(dlgLocalidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgLocalidadLayout.createSequentialGroup()
                                .addGroup(dlgLocalidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(30, 30, 30))
                            .addGroup(dlgLocalidadLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(dlgLocalidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtProvincia)
                            .addComponent(txtCanton)
                            .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgLocalidadLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtCodLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgLocalidadLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblL2)
                .addGap(51, 51, 51))
        );
        dlgLocalidadLayout.setVerticalGroup(
            dlgLocalidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgLocalidadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblL2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dlgLocalidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(dlgLocalidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgLocalidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(dlgLocalidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCanton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgLocalidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarL2)
                    .addComponent(btnGuardarL2))
                .addContainerGap())
        );

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TblLocalidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "cod_ciudad", "Pais", "Provincia", "Canton"
            }
        ));
        ScrlL1.setViewportView(TblLocalidad);

        btnAgregarL1.setText("Agregar");

        bntModificarL1.setText("Modificar");

        btnEliminarL1.setText("Eliminar");

        lblL1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lblL1.setText("Localidad");

        btnSalirL1.setText("Salir");

        btnBuscarL1.setText("Actualizar");

        jLabel5.setText("Buscar");

        jButton1.setText("Imprimir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBusquedaL1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarL1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntModificarL1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarL1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarL1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(btnSalirL1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalirL1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusquedaL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarL1)
                    .addComponent(bntModificarL1)
                    .addComponent(btnEliminarL1)
                    .addComponent(btnBuscarL1)
                    .addComponent(jLabel5)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ScrlL1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ScrlL1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProvinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProvinciaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrlL1;
    private javax.swing.JTable TblLocalidad;
    private javax.swing.JButton bntModificarL1;
    private javax.swing.JButton btnAgregarL1;
    private javax.swing.JButton btnBuscarL1;
    private javax.swing.JButton btnCancelarL2;
    private javax.swing.JButton btnEliminarL1;
    private javax.swing.JButton btnGuardarL2;
    private javax.swing.JButton btnSalirL1;
    private javax.swing.JDialog dlgLocalidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label lblL1;
    private javax.swing.JLabel lblL2;
    private javax.swing.JTextField txtBusquedaL1;
    private javax.swing.JTextField txtCanton;
    private javax.swing.JTextField txtCodLocal;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtProvincia;
    // End of variables declaration//GEN-END:variables
}
