/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class Vista_Vehiculo extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vista_Vehiculo
     */
    public Vista_Vehiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgVehiculo = new javax.swing.JDialog();
        lblV2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtRam = new javax.swing.JTextField();
        txtTonelaje = new javax.swing.JTextField();
        txtMatricula = new javax.swing.JTextField();
        txtPais = new javax.swing.JTextField();
        txtCanton = new javax.swing.JTextField();
        txtServicio = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        btnGuardarV2 = new javax.swing.JButton();
        btnCancelar2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        jdtFUltima = new com.toedter.calendar.JDateChooser();
        jdtFCaduce = new com.toedter.calendar.JDateChooser();
        lblV1 = new java.awt.Label();
        txtBusquedaV1 = new javax.swing.JTextField();
        btnBuscarV1 = new javax.swing.JButton();
        btnAgregarV1 = new javax.swing.JButton();
        bntModificarV1 = new javax.swing.JButton();
        btnSalirV1 = new javax.swing.JButton();
        scrVehiculo = new javax.swing.JScrollPane();
        tblVehiculo = new javax.swing.JTable();
        btnEliminarV1 = new javax.swing.JButton();

        lblV2.setText("Ingreso Vehiculo");

        jLabel2.setText("Ram o CPN");

        jLabel3.setText("Tonelaje");

        jLabel4.setText("N° Matricula");

        jLabel5.setText("Pais Origen");

        jLabel6.setText("Canton Matriculacion");

        jLabel7.setText("Fecha Ultima Matricula");

        jLabel8.setText("Tipo de Servicio");

        jLabel9.setText("Color de Vehiculo");

        jLabel10.setText("Fecha Caducidad de Matricula");

        txtRam.setText("jTextField2");

        txtTonelaje.setText("jTextField3");

        txtMatricula.setText("jTextField4");

        txtPais.setText("jTextField5");

        txtCanton.setText("jTextField6");

        txtServicio.setText("jTextField8");

        txtColor.setText("jTextField9");

        btnGuardarV2.setText("Guardar");

        btnCancelar2.setText("Cancelar");

        jLabel1.setText("Año Modelo");

        txtAnio.setText("jTextField1");

        javax.swing.GroupLayout dlgVehiculoLayout = new javax.swing.GroupLayout(dlgVehiculo.getContentPane());
        dlgVehiculo.getContentPane().setLayout(dlgVehiculoLayout);
        dlgVehiculoLayout.setHorizontalGroup(
            dlgVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgVehiculoLayout.createSequentialGroup()
                .addGroup(dlgVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgVehiculoLayout.createSequentialGroup()
                        .addGroup(dlgVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dlgVehiculoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(dlgVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(lblV2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)))
                            .addGroup(dlgVehiculoLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(btnGuardarV2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dlgVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTonelaje, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMatricula)
                            .addComponent(txtColor)
                            .addComponent(txtServicio)
                            .addComponent(txtPais)
                            .addComponent(txtRam, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(dlgVehiculoLayout.createSequentialGroup()
                                .addComponent(btnCancelar2)
                                .addGap(0, 33, Short.MAX_VALUE))
                            .addComponent(jdtFCaduce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jdtFUltima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCanton)))
                    .addGroup(dlgVehiculoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(91, 91, 91)
                        .addComponent(txtAnio)))
                .addContainerGap())
        );
        dlgVehiculoLayout.setVerticalGroup(
            dlgVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblV2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dlgVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTonelaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCanton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgVehiculoLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(9, 9, 9)
                        .addGroup(dlgVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(dlgVehiculoLayout.createSequentialGroup()
                                .addGroup(dlgVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(dlgVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addComponent(jLabel10))
                            .addComponent(jdtFCaduce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(dlgVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardarV2)
                            .addComponent(btnCancelar2))
                        .addGap(22, 22, 22))
                    .addGroup(dlgVehiculoLayout.createSequentialGroup()
                        .addComponent(jdtFUltima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblV1.setText("Vista Vehiculo");

        txtBusquedaV1.setText("Busqueda Vehiculo");

        btnBuscarV1.setText("Buscar");

        btnAgregarV1.setText("Agregar");

        bntModificarV1.setText("Modificar");

        btnSalirV1.setText("Salir");

        tblVehiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RAM o CPN", "Año de Modelo", "Tonelaje", "Matricula", "Pais de Origen", "Canton", "Fecha Ultima Matricula", "Tipo de Servicio ", "Color", "Fecha Caducidad Matricula"
            }
        ));
        scrVehiculo.setViewportView(tblVehiculo);
        if (tblVehiculo.getColumnModel().getColumnCount() > 0) {
            tblVehiculo.getColumnModel().getColumn(8).setResizable(false);
        }

        btnEliminarV1.setText("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBusquedaV1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEliminarV1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bntModificarV1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAgregarV1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuscarV1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalirV1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(scrVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(93, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusquedaV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarV1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarV1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntModificarV1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarV1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(btnSalirV1)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(70, Short.MAX_VALUE)
                    .addComponent(scrVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(49, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JDialog getDlgVehiculo() {
        return dlgVehiculo;
    }

    public void setDlgVehiculo(JDialog dlgVehiculo) {
        this.dlgVehiculo = dlgVehiculo;
    }

    public JButton getBntModificarV1() {
        return bntModificarV1;
    }

    public void setBntModificarV1(JButton bntModificarV1) {
        this.bntModificarV1 = bntModificarV1;
    }

    public JButton getBtnEliminarV1() {
        return btnEliminarV1;
    }

    public void setBtnEliminarV1(JButton btnEliminar) {
        this.btnEliminarV1 = btnEliminar;
    }

    public JButton getBtnCancelar2() {
        return btnCancelar2;
    }

    public void setBtnCancelar2(JButton btnCancelar2) {
        this.btnCancelar2 = btnCancelar2;
    }

    public JButton getBtnGuardarV2() {
        return btnGuardarV2;
    }

    public void setBtnGuardarV2(JButton btnGuardarV2) {
        this.btnGuardarV2 = btnGuardarV2;
    }

    public JButton getBtnAgregarV1() {
        return btnAgregarV1;
    }

    public void setBtnAgregarV1(JButton btnAgregarV1) {
        this.btnAgregarV1 = btnAgregarV1;
    }

    public JButton getBtnBuscarV1() {
        return btnBuscarV1;
    }

    public void setBtnBuscarV1(JButton btnBuscarV1) {
        this.btnBuscarV1 = btnBuscarV1;
    }

    public JButton getBtnSalirV1() {
        return btnSalirV1;
    }

    public void setBtnSalirV1(JButton btnSalirV1) {
        this.btnSalirV1 = btnSalirV1;
    }

    public JTable getTblVehiculo() {
        return tblVehiculo;
    }

    public void setTblVehiculo(JTable tblVehiculo) {
        this.tblVehiculo = tblVehiculo;
    }

    public JTextField getTxtBusquedaV1() {
        return txtBusquedaV1;
    }

    public void setTxtBusquedaV1(JTextField txtBusquedaV1) {
        this.txtBusquedaV1 = txtBusquedaV1;
    }

    public JTextField getTxtCanton() {
        return txtCanton;
    }

    public void setTxtCanton(JTextField txtCanton) {
        this.txtCanton = txtCanton;
    }

    public JTextField getTxtColor() {
        return txtColor;
    }

    public void setTxtColor(JTextField txtColor) {
        this.txtColor = txtColor;
    }

    public JTextField getTxtMatricula() {
        return txtMatricula;
    }

    public void setTxtMatricula(JTextField txtMatricula) {
        this.txtMatricula = txtMatricula;
    }

    public JTextField getTxtPais() {
        return txtPais;
    }

    public void setTxtPais(JTextField txtPais) {
        this.txtPais = txtPais;
    }

    public JTextField getTxtRam() {
        return txtRam;
    }

    public void setTxtRam(JTextField txtRam) {
        this.txtRam = txtRam;
    }

    public JTextField getTxtServicio() {
        return txtServicio;
    }

    public void setTxtServicio(JTextField txtServicio) {
        this.txtServicio = txtServicio;
    }

    public JTextField getTxtTonelaje() {
        return txtTonelaje;
    }

    public void setTxtTonelaje(JTextField txtTonelaje) {
        this.txtTonelaje = txtTonelaje;
    }

    public JTextField getTxtAnio() {
        return txtAnio;
    }

    public void setTxtAnio(JTextField txtAnio) {
        this.txtAnio = txtAnio;
    }

    public JDateChooser getJdtFCaduce() {
        return jdtFCaduce;
    }

    public void setJdtFCaduce(JDateChooser jdtFCaduce) {
        this.jdtFCaduce = jdtFCaduce;
    }

    public JDateChooser getJdtFUltima() {
        return jdtFUltima;
    }

    public void setJdtFUltima(JDateChooser jdtFUltima) {
        this.jdtFUltima = jdtFUltima;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntModificarV1;
    private javax.swing.JButton btnAgregarV1;
    private javax.swing.JButton btnBuscarV1;
    private javax.swing.JButton btnCancelar2;
    private javax.swing.JButton btnEliminarV1;
    private javax.swing.JButton btnGuardarV2;
    private javax.swing.JButton btnSalirV1;
    private javax.swing.JDialog dlgVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JDateChooser jdtFCaduce;
    private com.toedter.calendar.JDateChooser jdtFUltima;
    private java.awt.Label lblV1;
    private javax.swing.JLabel lblV2;
    private javax.swing.JScrollPane scrVehiculo;
    private javax.swing.JTable tblVehiculo;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtBusquedaV1;
    private javax.swing.JTextField txtCanton;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtRam;
    private javax.swing.JTextField txtServicio;
    private javax.swing.JTextField txtTonelaje;
    // End of variables declaration//GEN-END:variables
}
