/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class Vista_Servicio extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vista_Servicio
     */
    public Vista_Servicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogoServicio = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        lbln = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtcodServicio = new javax.swing.JTextField();
        txtkmsalida = new javax.swing.JTextField();
        txtkmllegada = new javax.swing.JTextField();
        txtidcliente = new javax.swing.JTextField();
        txtciudadSer = new javax.swing.JTextField();
        txtJfechaServicio = new com.toedter.calendar.JDateChooser();
        btnaceptarNS = new javax.swing.JButton();
        btncancelarNS = new javax.swing.JButton();
        txttotalServicio = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cbVehiculo = new javax.swing.JComboBox<>();
        txtempleado = new javax.swing.JTextField();
        btnbuscarEmpleado = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        cbxproducto = new javax.swing.JComboBox<>();
        cbxCategoria = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnAgregaNuevarCategoria = new javax.swing.JButton();
        btnAgregarNuevoProducto = new javax.swing.JButton();
        DialogoEmpreado = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaEligeEmpleado = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        btnElegirEmpleado = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaServicios = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnbuscarS = new javax.swing.JButton();
        btnnuevoS = new javax.swing.JButton();
        btnmodificarS = new javax.swing.JButton();
        btneliminarS = new javax.swing.JButton();
        btnimprimirS = new javax.swing.JButton();
        txtbuscarS = new javax.swing.JTextField();
        btnactualizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Nuevo Servicio");

        lbln.setText("N° :");

        jLabel5.setText("Cliente:");

        jLabel6.setText("Fecha :");

        jLabel7.setText("Ciudad :");

        jLabel8.setText("Vehiculo :");

        jLabel9.setText("Empleado :");

        jLabel10.setText("Km Salida :");

        jLabel11.setText("Km Llegada :");

        btnaceptarNS.setText("Aceptar");

        btncancelarNS.setText("Cancelar");

        jLabel12.setText("Total :");

        btnbuscarEmpleado.setText("Buscar");

        jLabel16.setText("Cantidad");

        cbxproducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Producto 1", "Producto 2", "Producto 3", "Producto 4" }));

        cbxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Categoria 1", "Categoria 2", "Categoria 3", "Categoria 4" }));

        jLabel4.setText("Producto:");

        jLabel14.setText("Categoria:");

        btnAgregaNuevarCategoria.setText("Agregar Nueva Categoria");

        btnAgregarNuevoProducto.setText("Agregar Nuevo Producto");

        javax.swing.GroupLayout DialogoServicioLayout = new javax.swing.GroupLayout(DialogoServicio.getContentPane());
        DialogoServicio.getContentPane().setLayout(DialogoServicioLayout);
        DialogoServicioLayout.setHorizontalGroup(
            DialogoServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogoServicioLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(DialogoServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(32, 32, 32)
                .addGroup(DialogoServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DialogoServicioLayout.createSequentialGroup()
                        .addGroup(DialogoServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtidcliente)
                            .addComponent(txtciudadSer)
                            .addComponent(txtJfechaServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(DialogoServicioLayout.createSequentialGroup()
                                .addGroup(DialogoServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogoServicioLayout.createSequentialGroup()
                                        .addComponent(txtempleado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnbuscarEmpleado))
                                    .addComponent(cbVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtkmsalida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtkmllegada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addGroup(DialogoServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogoServicioLayout.createSequentialGroup()
                                .addComponent(btncancelarNS)
                                .addGap(89, 89, 89)
                                .addComponent(btnaceptarNS))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogoServicioLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(txttotalServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogoServicioLayout.createSequentialGroup()
                                .addGroup(DialogoServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(DialogoServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbxproducto, 0, 164, Short.MAX_VALUE)
                                    .addComponent(cbxCategoria, 0, 164, Short.MAX_VALUE)
                                    .addComponent(txtcantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                    .addComponent(btnAgregaNuevarCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAgregarNuevoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogoServicioLayout.createSequentialGroup()
                                .addComponent(lbln)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtcodServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50))
                    .addGroup(DialogoServicioLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        DialogoServicioLayout.setVerticalGroup(
            DialogoServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogoServicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(DialogoServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DialogoServicioLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(DialogoServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtidcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogoServicioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DialogoServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcodServicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbln))))
                .addGap(18, 18, 18)
                .addGroup(DialogoServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DialogoServicioLayout.createSequentialGroup()
                        .addGroup(DialogoServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtJfechaServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(DialogoServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtciudadSer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(DialogoServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cbVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DialogoServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnbuscarEmpleado)
                            .addComponent(btnAgregarNuevoProducto)))
                    .addGroup(DialogoServicioLayout.createSequentialGroup()
                        .addGroup(DialogoServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregaNuevarCategoria)
                        .addGap(18, 18, 18)
                        .addGroup(DialogoServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(35, 35, 35)))
                .addGap(18, 18, 18)
                .addGroup(DialogoServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DialogoServicioLayout.createSequentialGroup()
                        .addGroup(DialogoServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtkmsalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(DialogoServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtkmllegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(txttotalServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogoServicioLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(DialogoServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btncancelarNS)
                            .addComponent(btnaceptarNS))
                        .addGap(20, 20, 20))))
        );

        tablaEligeEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula", "Nombre", "Apellido"
            }
        ));
        jScrollPane2.setViewportView(tablaEligeEmpleado);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Elija un Empleado");

        btnElegirEmpleado.setText("Elegir");

        javax.swing.GroupLayout DialogoEmpreadoLayout = new javax.swing.GroupLayout(DialogoEmpreado.getContentPane());
        DialogoEmpreado.getContentPane().setLayout(DialogoEmpreadoLayout);
        DialogoEmpreadoLayout.setHorizontalGroup(
            DialogoEmpreadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogoEmpreadoLayout.createSequentialGroup()
                .addGroup(DialogoEmpreadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DialogoEmpreadoLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel13))
                    .addGroup(DialogoEmpreadoLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnElegirEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        DialogoEmpreadoLayout.setVerticalGroup(
            DialogoEmpreadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogoEmpreadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 26, Short.MAX_VALUE)
                .addComponent(btnElegirEmpleado)
                .addContainerGap())
        );

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("SERVICIOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tablaServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Servicio", "Cliente", "Fecha", "Ciudad", "Vehiculo", "Empleado", "Km Salida", "Km Llegada", "Total"
            }
        ));
        jScrollPane1.setViewportView(tablaServicios);

        btnbuscarS.setText("Buscar");

        btnnuevoS.setText("Nuevo");

        btnmodificarS.setText("Modificar");

        btneliminarS.setText("Eliminar");

        btnimprimirS.setText("Imprimir");

        btnactualizar.setText("Actualizar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtbuscarS, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnbuscarS)
                .addGap(64, 64, 64)
                .addComponent(btnnuevoS, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnmodificarS, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btneliminarS, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(btnimprimirS, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbuscarS)
                    .addComponent(btnnuevoS)
                    .addComponent(btnmodificarS)
                    .addComponent(btneliminarS)
                    .addComponent(btnimprimirS)
                    .addComponent(txtbuscarS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnactualizar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnaceptarNS() {
        return btnaceptarNS;
    }

    public void setBtnaceptarNS(JButton btnaceptarNS) {
        this.btnaceptarNS = btnaceptarNS;
    }

    public JButton getBtnbuscarS() {
        return btnbuscarS;
    }

    public void setBtnbuscarS(JButton btnbuscarS) {
        this.btnbuscarS = btnbuscarS;
    }

    public JButton getBtncancelarNS() {
        return btncancelarNS;
    }

    public void setBtncancelarNS(JButton btncancelarNS) {
        this.btncancelarNS = btncancelarNS;
    }

    public JButton getBtneliminarS() {
        return btneliminarS;
    }

    public void setBtneliminarS(JButton btneliminarS) {
        this.btneliminarS = btneliminarS;
    }

    public JButton getBtnimprimirS() {
        return btnimprimirS;
    }

    public void setBtnimprimirS(JButton btnimprimirS) {
        this.btnimprimirS = btnimprimirS;
    }

    public JButton getBtnmodificarS() {
        return btnmodificarS;
    }

    public void setBtnmodificarS(JButton btnmodificarS) {
        this.btnmodificarS = btnmodificarS;
    }

    public JButton getBtnactualizar() {
        return btnactualizar;
    }

    public void setBtnactualizar(JButton btnactualizar) {
        this.btnactualizar = btnactualizar;
    }

    public JComboBox<String> getCbxCategoria() {
        return cbxCategoria;
    }

    public void setCbxCategoria(JComboBox<String> cbxCategoria) {
        this.cbxCategoria = cbxCategoria;
    }

    public JButton getBtnAgregaNuevarCategoria() {
        return btnAgregaNuevarCategoria;
    }

    public void setBtnAgregaNuevarCategoria(JButton btnAgregaNuevarCategoria) {
        this.btnAgregaNuevarCategoria = btnAgregaNuevarCategoria;
    }

    public JButton getBtnAgregarNuevoProducto() {
        return btnAgregarNuevoProducto;
    }

    public void setBtnAgregarNuevoProducto(JButton btnAgregarNuevoProducto) {
        this.btnAgregarNuevoProducto = btnAgregarNuevoProducto;
    }

    

    public JTextField getTxtcantidad() {
        return txtcantidad;
    }

    public void setTxtcantidad(JTextField txtcantidad) {
        this.txtcantidad = txtcantidad;
    }

    public JDialog getDialogoServicio() {
        return DialogoServicio;
    }

    public void setDialogoServicio(JDialog DialogoServicio) {
        this.DialogoServicio = DialogoServicio;
    }

    public JTable getTablaServicios() {
        return tablaServicios;
    }

    public void setTablaServicios(JTable tablaServicios) {
        this.tablaServicios = tablaServicios;
    }

    public JDateChooser getTxtJfechaServicio() {
        return txtJfechaServicio;
    }

    public void setTxtJfechaServicio(JDateChooser txtJfechaServicio) {
        this.txtJfechaServicio = txtJfechaServicio;
    }

    public JTextField getTxtbuscarS() {
        return txtbuscarS;
    }

    public void setTxtbuscarS(JTextField txtbuscarS) {
        this.txtbuscarS = txtbuscarS;
    }

    public JTextField getTxtciudadSer() {
        return txtciudadSer;
    }

    public void setTxtciudadSer(JTextField txtciudadSer) {
        this.txtciudadSer = txtciudadSer;
    }

    public JTextField getTxttotalServicio() {
        return txttotalServicio;
    }

    public void setTxttotalServicio(JTextField txttotalServicio) {
        this.txttotalServicio = txttotalServicio;
    }

    public JTextField getTxtcodServicio() {
        return txtcodServicio;
    }

    public void setTxtcodServicio(JTextField txtcodServicio) {
        this.txtcodServicio = txtcodServicio;
    }

    public JLabel getLbln() {
        return lbln;
    }

    public void setLbln(JLabel lbln) {
        this.lbln = lbln;
    }

    public JTextField getTxtempleado() {
        return txtempleado;
    }

    public void setTxtempleado(JTextField txtempleado) {
        this.txtempleado = txtempleado;
    }

    public JButton getBtnbuscarEmpleado() {
        return btnbuscarEmpleado;
    }

    public void setBtnbuscarEmpleado(JButton btnbuscarEmpleado) {
        this.btnbuscarEmpleado = btnbuscarEmpleado;
    }

    public JDialog getDialogoEmpreado() {
        return DialogoEmpreado;
    }

    public void setDialogoEmpreado(JDialog DialogoEmpreado) {
        this.DialogoEmpreado = DialogoEmpreado;
    }

    public JButton getBtnElegirEmpleado() {
        return btnElegirEmpleado;
    }

    public void setBtnElegirEmpleado(JButton btnElegirEmpleado) {
        this.btnElegirEmpleado = btnElegirEmpleado;
    }

    public JTable getTablaEligeEmpleado() {
        return tablaEligeEmpleado;
    }

    public void setTablaEligeEmpleado(JTable tablaEligeEmpleado) {
        this.tablaEligeEmpleado = tablaEligeEmpleado;
    }

    public JComboBox<String> getCbVehiculo() {
        return cbVehiculo;
    }

    public void setCbVehiculo(JComboBox<String> cbVehiculo) {
        this.cbVehiculo = cbVehiculo;
    }

    public JComboBox<String> getCbxproducto() {
        return cbxproducto;
    }

    public void setCbxproducto(JComboBox<String> cbxproducto) {
        this.cbxproducto = cbxproducto;
    }


    public JTextField getTxtidcliente() {
        return txtidcliente;
    }

    public void setTxtidcliente(JTextField txtidcliente) {
        this.txtidcliente = txtidcliente;
    }

    public JTextField getTxtkmllegada() {
        return txtkmllegada;
    }

    public void setTxtkmllegada(JTextField txtkmllegada) {
        this.txtkmllegada = txtkmllegada;
    }

    public JTextField getTxtkmsalida() {
        return txtkmsalida;
    }

    public void setTxtkmsalida(JTextField txtkmsalida) {
        this.txtkmsalida = txtkmsalida;
    }

    public JButton getBtnnuevoS() {
        return btnnuevoS;
    }

    public void setBtnnuevoS(JButton btnnuevoS) {
        this.btnnuevoS = btnnuevoS;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog DialogoEmpreado;
    private javax.swing.JDialog DialogoServicio;
    private javax.swing.JButton btnAgregaNuevarCategoria;
    private javax.swing.JButton btnAgregarNuevoProducto;
    private javax.swing.JButton btnElegirEmpleado;
    private javax.swing.JButton btnaceptarNS;
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnbuscarEmpleado;
    private javax.swing.JButton btnbuscarS;
    private javax.swing.JButton btncancelarNS;
    private javax.swing.JButton btneliminarS;
    private javax.swing.JButton btnimprimirS;
    private javax.swing.JButton btnmodificarS;
    private javax.swing.JButton btnnuevoS;
    private javax.swing.JComboBox<String> cbVehiculo;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JComboBox<String> cbxproducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbln;
    private javax.swing.JTable tablaEligeEmpleado;
    private javax.swing.JTable tablaServicios;
    private com.toedter.calendar.JDateChooser txtJfechaServicio;
    private javax.swing.JTextField txtbuscarS;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtciudadSer;
    private javax.swing.JTextField txtcodServicio;
    private javax.swing.JTextField txtempleado;
    private javax.swing.JTextField txtidcliente;
    private javax.swing.JTextField txtkmllegada;
    private javax.swing.JTextField txtkmsalida;
    private javax.swing.JTextField txttotalServicio;
    // End of variables declaration//GEN-END:variables
}
