/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class Vista_Localidad extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vista_Localidad
     */
    public Vista_Localidad() {
        initComponents();
    }

    public JTable getTblLocalidad() {
        return TblLocalidad;
    }

    public void setTblLocalidad(JTable TblLocalidad) {
        this.TblLocalidad = TblLocalidad;
    }

    public JButton getBntModificarL1() {
        return bntModificarL1;
    }

    public void setBntModificarL1(JButton bntModificarL1) {
        this.bntModificarL1 = bntModificarL1;
    }

    public JButton getBtnAgregarL1() {
        return btnAgregarL1;
    }

    public void setBtnAgregarL1(JButton btnAgregarL1) {
        this.btnAgregarL1 = btnAgregarL1;
    }

    public JButton getBtnBuscarL1() {
        return btnBuscarL1;
    }

    public void setBtnBuscarL1(JButton btnBuscarL1) {
        this.btnBuscarL1 = btnBuscarL1;
    }

    public JButton getBtnCancelarL2() {
        return btnCancelarL2;
    }

    public void setBtnCancelarL2(JButton btnCancelarL2) {
        this.btnCancelarL2 = btnCancelarL2;
    }

    public JButton getBtnEliminarL1() {
        return btnEliminarL1;
    }

    public void setBtnEliminarL1(JButton btnEliminarV1) {
        this.btnEliminarL1 = btnEliminarV1;
    }

    public JButton getBtnGuardarL2() {
        return btnGuardarL2;
    }

    public void setBtnGuardarL2(JButton btnGuardarL2) {
        this.btnGuardarL2 = btnGuardarL2;
    }

    public JButton getBtnSalirL1() {
        return btnSalirL1;
    }

    public void setBtnSalirL1(JButton btnSalirL1) {
        this.btnSalirL1 = btnSalirL1;
    }

    public JDialog getDlgLocalidad() {
        return dlgLocalidad;
    }

    public void setDlgLocalidad(JDialog dlgLocalidad) {
        this.dlgLocalidad = dlgLocalidad;
    }

    public JTextField getTxtBusquedaL1() {
        return txtBusquedaL1;
    }

    public void setTxtBusquedaL1(JTextField txtBusquedaL1) {
        this.txtBusquedaL1 = txtBusquedaL1;
    }

    public JTextField getTxtCanton() {
        return txtCanton;
    }

    public void setTxtCanton(JTextField txtCanton) {
        this.txtCanton = txtCanton;
    }

    public JTextField getTxtCodLocal() {
        return txtCodLocal;
    }

    public void setTxtCodLocal(JTextField txtCodLocal) {
        this.txtCodLocal = txtCodLocal;
    }

    public JTextField getTxtPais() {
        return txtPais;
    }

    public void setTxtPais(JTextField txtPais) {
        this.txtPais = txtPais;
    }

    public JTextField getTxtProvincia() {
        return txtProvincia;
    }

    public void setTxtProvincia(JTextField txtProvincia) {
        this.txtProvincia = txtProvincia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgLocalidad = new javax.swing.JDialog();
        lblL2 = new javax.swing.JLabel();
        txtProvincia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCanton = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPais = new javax.swing.JTextField();
        txtCodLocal = new javax.swing.JTextField();
        btnGuardarL2 = new javax.swing.JButton();
        btnCancelarL2 = new javax.swing.JButton();
        btnEliminarL1 = new javax.swing.JButton();
        lblL1 = new java.awt.Label();
        txtBusquedaL1 = new javax.swing.JTextField();
        btnBuscarL1 = new javax.swing.JButton();
        btnAgregarL1 = new javax.swing.JButton();
        bntModificarL1 = new javax.swing.JButton();
        btnSalirL1 = new javax.swing.JButton();
        ScrlL1 = new javax.swing.JScrollPane();
        TblLocalidad = new javax.swing.JTable();

        lblL2.setText("Ingreso Localidad");

        txtProvincia.setText("jTextField3");

        jLabel2.setText("Codigo Localidad");

        txtCanton.setText("jTextField4");

        jLabel3.setText("Provincia");

        jLabel4.setText("Canton");

        jLabel1.setText("Pais");

        txtPais.setText("jTextField1");

        txtCodLocal.setText("jTextField2");

        btnGuardarL2.setText("Guardar");

        btnCancelarL2.setText("Cancelar");

        javax.swing.GroupLayout dlgLocalidadLayout = new javax.swing.GroupLayout(dlgLocalidad.getContentPane());
        dlgLocalidad.getContentPane().setLayout(dlgLocalidadLayout);
        dlgLocalidadLayout.setHorizontalGroup(
            dlgLocalidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgLocalidadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgLocalidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgLocalidadLayout.createSequentialGroup()
                        .addGroup(dlgLocalidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dlgLocalidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProvincia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(txtCanton)
                            .addComponent(txtCodLocal, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(dlgLocalidadLayout.createSequentialGroup()
                        .addComponent(lblL2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(dlgLocalidadLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(65, 65, 65)
                        .addComponent(txtPais))))
            .addGroup(dlgLocalidadLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnGuardarL2)
                .addGap(29, 29, 29)
                .addComponent(btnCancelarL2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dlgLocalidadLayout.setVerticalGroup(
            dlgLocalidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgLocalidadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblL2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgLocalidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgLocalidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgLocalidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgLocalidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCanton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(dlgLocalidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarL2)
                    .addComponent(btnCancelarL2))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnEliminarL1.setText("Eliminar");

        lblL1.setText("Vista Localidad");

        txtBusquedaL1.setText("Busqueda Vehiculo");

        btnBuscarL1.setText("Buscar");

        btnAgregarL1.setText("Agregar");

        bntModificarL1.setText("Modificar");

        btnSalirL1.setText("Salir");

        TblLocalidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "cod_ciudad", "Pais", "Provincia", "Canton"
            }
        ));
        ScrlL1.setViewportView(TblLocalidad);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBusquedaL1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarL1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarL1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntModificarL1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSalirL1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarL1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(12, Short.MAX_VALUE)
                    .addComponent(ScrlL1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(96, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusquedaL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarL1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarL1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntModificarL1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarL1)
                .addGap(45, 45, 45)
                .addComponent(btnSalirL1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(70, Short.MAX_VALUE)
                    .addComponent(ScrlL1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrlL1;
    private javax.swing.JTable TblLocalidad;
    private javax.swing.JButton bntModificarL1;
    private javax.swing.JButton btnAgregarL1;
    private javax.swing.JButton btnBuscarL1;
    private javax.swing.JButton btnCancelarL2;
    private javax.swing.JButton btnEliminarL1;
    private javax.swing.JButton btnGuardarL2;
    private javax.swing.JButton btnSalirL1;
    private javax.swing.JDialog dlgLocalidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private java.awt.Label lblL1;
    private javax.swing.JLabel lblL2;
    private javax.swing.JTextField txtBusquedaL1;
    private javax.swing.JTextField txtCanton;
    private javax.swing.JTextField txtCodLocal;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtProvincia;
    // End of variables declaration//GEN-END:variables
}
