/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author daysi
 */
public class VistaProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public VistaProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoproducto = new javax.swing.JDesktopPane();
        jButton6 = new javax.swing.JButton();
        txtcate1 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        txtnomcate1 = new javax.swing.JTextField();
        txtdescripcion1 = new javax.swing.JTextField();
        txtcodproducto1 = new javax.swing.JTextField();
        txtnompro1 = new javax.swing.JTextField();
        txtunidadm1 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jButton6.setText("IMPRIMIR");

        txtcate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcate1ActionPerformed(evt);
            }
        });

        jButton7.setText("VIZUALIZAR");

        jButton8.setText("AGREGAR");

        jButton9.setText("MODIFICAR");

        jLabel7.setText("CODIGO CATEGORIA");

        jLabel8.setText("NOMBRE CATEGORIA");

        jLabel9.setText("DESCRIPCION");

        jLabel10.setText("NOMBRE PRODUCTO");

        jLabel11.setText("UNIDAD DE MEDIDA");

        jLabel12.setText("CODIGO PRODUCTO");

        jButton10.setText("ELEIMINAR");

        dialogoproducto.setLayer(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dialogoproducto.setLayer(txtcate1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dialogoproducto.setLayer(jButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dialogoproducto.setLayer(txtnomcate1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dialogoproducto.setLayer(txtdescripcion1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dialogoproducto.setLayer(txtcodproducto1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dialogoproducto.setLayer(txtnompro1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dialogoproducto.setLayer(txtunidadm1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dialogoproducto.setLayer(jButton8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dialogoproducto.setLayer(jButton9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dialogoproducto.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dialogoproducto.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dialogoproducto.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dialogoproducto.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dialogoproducto.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dialogoproducto.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dialogoproducto.setLayer(jButton10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dialogoproductoLayout = new javax.swing.GroupLayout(dialogoproducto);
        dialogoproducto.setLayout(dialogoproductoLayout);
        dialogoproductoLayout.setHorizontalGroup(
            dialogoproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoproductoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(dialogoproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(34, 34, 34)
                .addGroup(dialogoproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtcate1)
                    .addComponent(txtnomcate1)
                    .addComponent(txtdescripcion1)
                    .addComponent(txtcodproducto1)
                    .addComponent(txtnompro1)
                    .addComponent(txtunidadm1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addGroup(dialogoproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(dialogoproductoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton9)))
                .addGap(21, 21, 21))
        );
        dialogoproductoLayout.setVerticalGroup(
            dialogoproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoproductoLayout.createSequentialGroup()
                .addGroup(dialogoproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoproductoLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(dialogoproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jButton8)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoproductoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtcate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(dialogoproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoproductoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(dialogoproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtnomcate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(dialogoproductoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtdescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jButton10)
                .addGap(20, 20, 20)
                .addGroup(dialogoproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txtcodproducto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(dialogoproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtnompro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addGap(31, 31, 31)
                .addGroup(dialogoproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtunidadm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO CATEGORIA", "NOMBRE CATEGORIA", "DESCRIPCION", "CODIGO PRODUCTO", "NOMBRE PRODUCTO", "UNIDAD DE MEDIDA"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcate1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dialogoproducto;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtcate1;
    private javax.swing.JTextField txtcodproducto1;
    private javax.swing.JTextField txtdescripcion1;
    private javax.swing.JTextField txtnomcate1;
    private javax.swing.JTextField txtnompro1;
    private javax.swing.JTextField txtunidadm1;
    // End of variables declaration//GEN-END:variables
}
