/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class Vista_Perfil extends javax.swing.JFrame {

    /**
     * Creates new form Vista_Perfil
     */
    public Vista_Perfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        plblfoto = new javax.swing.JLabel();
        datachoser = new com.toedter.calendar.JDateChooser();
        btnEditarPerfil = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        plblidempelado = new javax.swing.JLabel();
        ptxtNombre = new javax.swing.JTextField();
        ptxtApellido = new javax.swing.JTextField();
        ptxtTelf = new javax.swing.JTextField();
        ptxtDireccion = new javax.swing.JTextField();
        btnExaminar = new javax.swing.JButton();
        btnpGuardar = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtpalabra = new javax.swing.JTextField();
        btnpVerContra = new javax.swing.JButton();
        passoculto = new javax.swing.JPasswordField();
        txtcontra1 = new javax.swing.JTextField();
        passoculto2 = new javax.swing.JPasswordField();
        cmbSexo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblVentas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombre: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 70, 16));

        jLabel3.setText("Apellido: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel4.setText("Usuario: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 19));

        jLabel5.setText("Fecha Nacmiento: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel6.setText("Direccion: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, 21));

        jLabel7.setText("Telefono: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        plblfoto.setText("foto");
        plblfoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        jPanel1.add(plblfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 48, 172, 137));

        datachoser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(datachoser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 130, -1));

        btnEditarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/Editar.PNG"))); // NOI18N
        btnEditarPerfil.setBorderPainted(false);
        btnEditarPerfil.setContentAreaFilled(false);
        jPanel1.add(btnEditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, 70, 40));

        jLabel8.setText("ID Empleado: ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 23, -1, -1));

        plblidempelado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(plblidempelado, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 23, 75, 19));
        jPanel1.add(ptxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 130, -1));
        jPanel1.add(ptxtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 130, -1));
        jPanel1.add(ptxtTelf, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 130, -1));
        jPanel1.add(ptxtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 130, -1));

        btnExaminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/Examinar.png"))); // NOI18N
        btnExaminar.setBorderPainted(false);
        btnExaminar.setContentAreaFilled(false);
        jPanel1.add(btnExaminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 100, -1));

        btnpGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/AceptarP.png"))); // NOI18N
        btnpGuardar.setBorderPainted(false);
        btnpGuardar.setContentAreaFilled(false);
        jPanel1.add(btnpGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, 100, -1));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 130, -1));

        jLabel9.setText("Contraseña: ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        jLabel10.setText("Repita Contraseña: ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        jLabel11.setText("Palabra: ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 144, -1, -1));
        jPanel1.add(txtpalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 164, 130, -1));

        btnpVerContra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/ver.png"))); // NOI18N
        btnpVerContra.setBorderPainted(false);
        btnpVerContra.setContentAreaFilled(false);
        jPanel1.add(btnpVerContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 30, 20));
        jPanel1.add(passoculto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 130, -1));
        jPanel1.add(txtcontra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 130, -1));
        jPanel1.add(passoculto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 130, -1));

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Hombre", "Mujer" }));
        jPanel1.add(cmbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 130, 20));

        jLabel12.setText("Sexo: ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        TblVentas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        TblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Servicio", "Fecha", "Cliente", "Ciudad", "Chofer", "Vehiculo", "Precio"
            }
        ));
        jScrollPane1.setViewportView(TblVentas);

        jPanel2.setBackground(new java.awt.Color(255, 231, 47));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("PERFIL");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(416, 416, 416))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("RESUMEN VENTAS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(355, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(345, 345, 345))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JDateChooser getDatachoser() {
        return datachoser;
    }

    public void setDatachoser(JDateChooser datachoser) {
        this.datachoser = datachoser;
    }

    public JTable getjTable1() {
        return TblVentas;
    }

    public void setjTable1(JTable jTable1) {
        this.TblVentas = jTable1;
    }

    public JTextField getTxtUsuario() {
        return txtUsuario;
    }

    public JButton getBtnpVerContra() {
        return btnpVerContra;
    }

    public void setBtnpVerContra(JButton btnpVerContra) {
        this.btnpVerContra = btnpVerContra;
    }

    public JPasswordField getPassoculto() {
        return passoculto;
    }

    public void setPassoculto(JPasswordField passoculto) {
        this.passoculto = passoculto;
    }

    public JTextField getTxtcontra1() {
        return txtcontra1;
    }

    public void setTxtcontra1(JTextField txtcontra1) {
        this.txtcontra1 = txtcontra1;
    }

    public JTextField getTxtpalabra() {
        return txtpalabra;
    }

    public void setTxtpalabra(JTextField txtpalabra) {
        this.txtpalabra = txtpalabra;
    }

    public void setTxtUsuario(JTextField txtUsuario) {
        this.txtUsuario = txtUsuario;
    }

    public JPasswordField getPassoculto2() {
        return passoculto2;
    }

    public void setPassoculto2(JPasswordField passoculto2) {
        this.passoculto2 = passoculto2;
    }

    public JComboBox<String> getCmbSexo() {
        return cmbSexo;
    }

    public void setCmbSexo(JComboBox<String> cmbSexo) {
        this.cmbSexo = cmbSexo;
    }

    public JLabel getPlblfoto() {
        return plblfoto;
    }

    public void setPlblfoto(JLabel plblfoto) {
        this.plblfoto = plblfoto;
    }

    public JButton getBtnEditarPerfil() {
        return btnEditarPerfil;
    }

    public void setBtnEditarPerfil(JButton btnEditarPerfil) {
        this.btnEditarPerfil = btnEditarPerfil;
    }

    public JLabel getPlblidempelado() {
        return plblidempelado;
    }

    public void setPlblidempelado(JLabel plblidempelado) {
        this.plblidempelado = plblidempelado;
    }


    public JTable getTblVentas() {
        return TblVentas;
    }

    public void setTblVentas(JTable TblVentas) {
        this.TblVentas = TblVentas;
    }

    public JButton getBtnExaminar() {
        return btnExaminar;
    }

    public void setBtnExaminar(JButton btnExaminar) {
        this.btnExaminar = btnExaminar;
    }

    public JButton getBtnpGuardar() {
        return btnpGuardar;
    }

    public void setBtnpGuardar(JButton btnpGuardar) {
        this.btnpGuardar = btnpGuardar;
    }

    public JTextField getPtxtApellido() {
        return ptxtApellido;
    }

    public void setPtxtApellido(JTextField ptxtApellido) {
        this.ptxtApellido = ptxtApellido;
    }

    public JTextField getPtxtDireccion() {
        return ptxtDireccion;
    }

    public void setPtxtDireccion(JTextField ptxtDireccion) {
        this.ptxtDireccion = ptxtDireccion;
    }

    public JTextField getPtxtNombre() {
        return ptxtNombre;
    }

    public void setPtxtNombre(JTextField ptxtNombre) {
        this.ptxtNombre = ptxtNombre;
    }

    public JTextField getPtxtTelf() {
        return ptxtTelf;
    }

    public void setPtxtTelf(JTextField ptxtTelf) {
        this.ptxtTelf = ptxtTelf;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblVentas;
    private javax.swing.JButton btnEditarPerfil;
    private javax.swing.JButton btnExaminar;
    private javax.swing.JButton btnpGuardar;
    private javax.swing.JButton btnpVerContra;
    private javax.swing.JComboBox<String> cmbSexo;
    private com.toedter.calendar.JDateChooser datachoser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField passoculto;
    private javax.swing.JPasswordField passoculto2;
    private javax.swing.JLabel plblfoto;
    private javax.swing.JLabel plblidempelado;
    private javax.swing.JTextField ptxtApellido;
    private javax.swing.JTextField ptxtDireccion;
    private javax.swing.JTextField ptxtNombre;
    private javax.swing.JTextField ptxtTelf;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtcontra1;
    private javax.swing.JTextField txtpalabra;
    // End of variables declaration//GEN-END:variables
}
