/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class Vista_Empleado extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vista_Empleado
     */
    public Vista_Empleado() {
        initComponents();
    }

    public JComboBox<String> getCmbCargo() {
        return CmbCargo;
    }

    public void setCmbCargo(JComboBox<String> CmbCargo) {
        this.CmbCargo = CmbCargo;
    }

    public JDialog getDialogoEmpleado() {
        return DialogoEmpleado;
    }

    public void setDialogoEmpleado(JDialog DialogoEmpleado) {
        this.DialogoEmpleado = DialogoEmpleado;
    }

    public JButton getBtnAceptarE() {
        return btnAceptarE;
    }

    public void setBtnAceptarE(JButton btnAceptarE) {
        this.btnAceptarE = btnAceptarE;
    }

    public JButton getBtnActualizarE() {
        return btnActualizarE;
    }

    public void setBtnActualizarE(JButton btnActualizarE) {
        this.btnActualizarE = btnActualizarE;
    }

    public JButton getBtnCancelarE() {
        return btnCancelarE;
    }

    public void setBtnCancelarE(JButton btnCancelarE) {
        this.btnCancelarE = btnCancelarE;
    }

    public JButton getBtnEditarE() {
        return btnEditarE;
    }

    public void setBtnEditarE(JButton btnEditarE) {
        this.btnEditarE = btnEditarE;
    }

    public JButton getBtnEliminarE() {
        return btnEliminarE;
    }

    public void setBtnEliminarE(JButton btnEliminarE) {
        this.btnEliminarE = btnEliminarE;
    }

    public JButton getBtnExaminarE() {
        return btnExaminarE;
    }

    public void setBtnExaminarE(JButton btnExaminarE) {
        this.btnExaminarE = btnExaminarE;
    }

    public JButton getBtnImprimirE() {
        return btnImprimirE;
    }

    public void setBtnImprimirE(JButton btnImprimirE) {
        this.btnImprimirE = btnImprimirE;
    }

    public JButton getBtnNuevoE() {
        return btnNuevoE;
    }

    public void setBtnNuevoE(JButton btnNuevoE) {
        this.btnNuevoE = btnNuevoE;
    }

    public JDateChooser getDchfechaE() {
        return dchfechaE;
    }

    public void setDchfechaE(JDateChooser dchfechaE) {
        this.dchfechaE = dchfechaE;
    }

    public JLabel getLblfotoE() {
        return lblfotoE;
    }

    public void setLblfotoE(JLabel lblfotoE) {
        this.lblfotoE = lblfotoE;
    }

    public JTable getTblEmpleado() {
        return tblEmpleado;
    }

    public void setTblEmpleado(JTable tblEmpleado) {
        this.tblEmpleado = tblEmpleado;
    }

    public JTextField getTxtBuscarE() {
        return txtBuscarE;
    }

    public void setTxtBuscarE(JTextField txtBuscarE) {
        this.txtBuscarE = txtBuscarE;
    }

    public JTextField getTxtapellidoE() {
        return txtapellidoE;
    }

    public void setTxtapellidoE(JTextField txtapellidoE) {
        this.txtapellidoE = txtapellidoE;
    }

    public JTextField getTxtcedulaE() {
        return txtcedulaE;
    }

    public void setTxtcedulaE(JTextField txtcedulaE) {
        this.txtcedulaE = txtcedulaE;
    }

    public JTextField getTxtdirecE() {
        return txtdirecE;
    }

    public void setTxtdirecE(JTextField txtdirecE) {
        this.txtdirecE = txtdirecE;
    }

    public JLabel getTxtid() {
        return txtid;
    }

    public void setTxtid(JLabel txtid) {
        this.txtid = txtid;
    }

    public JTextField getTxtidEmpleado() {
        return txtidEmpleado;
    }

    public void setTxtidEmpleado(JTextField txtidEmpleado) {
        this.txtidEmpleado = txtidEmpleado;
    }

    public JTextField getTxtnombreE() {
        return txtnombreE;
    }

    public void setTxtnombreE(JTextField txtnombreE) {
        this.txtnombreE = txtnombreE;
    }

    public JTextField getTxtsueldoE() {
        return txtsueldoE;
    }

    public void setTxtsueldoE(JTextField txtsueldoE) {
        this.txtsueldoE = txtsueldoE;
    }

    public JTextField getTxttelfE() {
        return txttelfE;
    }

    public void setTxttelfE(JTextField txttelfE) {
        this.txttelfE = txttelfE;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogoEmpleado = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblfotoE = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnExaminarE = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtsueldoE = new javax.swing.JTextField();
        CmbCargo = new javax.swing.JComboBox<>();
        txttelfE = new javax.swing.JTextField();
        txtdirecE = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnAceptarE = new javax.swing.JButton();
        dchfechaE = new com.toedter.calendar.JDateChooser();
        txtid = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcedulaE = new javax.swing.JTextField();
        btnCancelarE = new javax.swing.JButton();
        txtapellidoE = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtnombreE = new javax.swing.JTextField();
        txtidEmpleado = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarE = new javax.swing.JTextField();
        btnNuevoE = new javax.swing.JButton();
        btnEditarE = new javax.swing.JButton();
        btnEliminarE = new javax.swing.JButton();
        btnActualizarE = new javax.swing.JButton();
        btnImprimirE = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleado = new javax.swing.JTable();
        lblMensaje = new javax.swing.JLabel();

        DialogoEmpleado.setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 155, 28));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setText("NUEVO EMPLEADO");

        jPanel3.setBackground(new java.awt.Color(241, 218, 154));

        jLabel4.setText("Nombre:");

        lblfotoE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 155, 28), 2));

        jLabel5.setText("Fecha:");

        btnExaminarE.setText("Examinar");

        jLabel11.setText("Cargo:");

        jLabel13.setText("Sueldo:");

        CmbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "........", "Chofer", "Mecanico", " " }));

        jLabel10.setText("Direccion:");

        btnAceptarE.setText("ACEPTAR");

        txtid.setText("ID:");

        jLabel6.setText("Apellido:");

        btnCancelarE.setText("CANCELAR");

        jLabel3.setText("Cedula:");

        jLabel8.setText("Teléfono:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtsueldoE, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CmbCargo, javax.swing.GroupLayout.Alignment.LEADING, 0, 160, Short.MAX_VALUE)
                            .addComponent(txtdirecE, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcedulaE, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnombreE, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtapellidoE, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dchfechaE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txttelfE, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblfotoE, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtid)
                                        .addGap(35, 35, 35)
                                        .addComponent(txtidEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnExaminarE)
                                .addGap(97, 97, 97))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptarE)
                .addGap(49, 49, 49)
                .addComponent(btnCancelarE)
                .addGap(144, 144, 144))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcedulaE, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(4, 4, 4)
                .addComponent(txtnombreE, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtapellidoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dchfechaE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txttelfE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(4, 4, 4)
                .addComponent(txtdirecE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CmbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtsueldoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAceptarE)
                            .addComponent(btnCancelarE))
                        .addContainerGap())))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblfotoE, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExaminarE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout DialogoEmpleadoLayout = new javax.swing.GroupLayout(DialogoEmpleado.getContentPane());
        DialogoEmpleado.getContentPane().setLayout(DialogoEmpleadoLayout);
        DialogoEmpleadoLayout.setHorizontalGroup(
            DialogoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogoEmpleadoLayout.setVerticalGroup(
            DialogoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Buscar");

        btnNuevoE.setText("Nuevo");

        btnEditarE.setText("Editar");

        btnEliminarE.setText("Eliminar");

        btnActualizarE.setText("Actualizar");

        btnImprimirE.setText("Imprimir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBuscarE, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNuevoE, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditarE, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarE, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActualizarE, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(btnImprimirE, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscarE, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevoE)
                    .addComponent(btnEditarE)
                    .addComponent(btnEliminarE)
                    .addComponent(btnActualizarE)
                    .addComponent(btnImprimirE))
                .addContainerGap())
        );

        tblEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Empleado", "Cedula", "Nombre", "Apellido", "Fecha Nac", "Direccion", "Telefono", "Cargo", "Sueldo", "foto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEmpleado);

        lblMensaje.setText("Sistema Personas :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(lblMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbCargo;
    private javax.swing.JDialog DialogoEmpleado;
    private javax.swing.JButton btnAceptarE;
    private javax.swing.JButton btnActualizarE;
    private javax.swing.JButton btnCancelarE;
    private javax.swing.JButton btnEditarE;
    private javax.swing.JButton btnEliminarE;
    private javax.swing.JButton btnExaminarE;
    private javax.swing.JButton btnImprimirE;
    private javax.swing.JButton btnNuevoE;
    private com.toedter.calendar.JDateChooser dchfechaE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblfotoE;
    private javax.swing.JTable tblEmpleado;
    private javax.swing.JTextField txtBuscarE;
    private javax.swing.JTextField txtapellidoE;
    private javax.swing.JTextField txtcedulaE;
    private javax.swing.JTextField txtdirecE;
    private javax.swing.JLabel txtid;
    private javax.swing.JTextField txtidEmpleado;
    private javax.swing.JTextField txtnombreE;
    private javax.swing.JTextField txtsueldoE;
    private javax.swing.JTextField txttelfE;
    // End of variables declaration//GEN-END:variables
}
