/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class VistaProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaProducto
     */
    public VistaProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgProducto = new javax.swing.JDialog();
        Lbl1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcodprod = new javax.swing.JTextField();
        txtNombreprod = new javax.swing.JTextField();
        txtPrecioprod = new javax.swing.JTextField();
        btnAceptarprod = new javax.swing.JButton();
        btnCancelarprod = new javax.swing.JButton();
        CbCategoriaprod = new javax.swing.JComboBox<>();
        lblimagenprod = new javax.swing.JLabel();
        btnExaminar = new javax.swing.JButton();
        txtCostoprod = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfdescripcionprod = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblproducto = new javax.swing.JTable();
        lblmensajes = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnnuevoprod = new javax.swing.JButton();
        btneditarProd = new javax.swing.JButton();
        btneliminarProd = new javax.swing.JButton();
        btnimprimirProd = new javax.swing.JButton();
        btnactualizarProd = new javax.swing.JButton();
        txtbuscarProd = new javax.swing.JTextField();
        btnCerrarJFProd = new javax.swing.JButton();

        Lbl1.setText("Codigo:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Descripcion:");

        jLabel5.setText("Precio:");

        jLabel2.setText("Costo:");

        jLabel6.setText("Categoria:");

        btnAceptarprod.setText("Aceptar");
        btnAceptarprod.setOpaque(false);

        btnCancelarprod.setText("Cancelar");

        CbCategoriaprod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "....", "Viveres", "Lacteos", "Cosmeticos", "Galletas", "Dulces", "Bebidas" }));

        lblimagenprod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnExaminar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnExaminar.setText("Examinar...");

        tfdescripcionprod.setColumns(20);
        tfdescripcionprod.setLineWrap(true);
        tfdescripcionprod.setRows(5);
        jScrollPane2.setViewportView(tfdescripcionprod);

        javax.swing.GroupLayout dlgProductoLayout = new javax.swing.GroupLayout(dlgProducto.getContentPane());
        dlgProducto.getContentPane().setLayout(dlgProductoLayout);
        dlgProductoLayout.setHorizontalGroup(
            dlgProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgProductoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(dlgProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgProductoLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnAceptarprod, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(btnCancelarprod, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(dlgProductoLayout.createSequentialGroup()
                        .addGroup(dlgProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(Lbl1))
                        .addGap(18, 18, 18)
                        .addGroup(dlgProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcodprod, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCostoprod, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(dlgProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNombreprod, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                            .addGroup(dlgProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(CbCategoriaprod, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPrecioprod, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(dlgProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblimagenprod, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExaminar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))))
        );
        dlgProductoLayout.setVerticalGroup(
            dlgProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgProductoLayout.createSequentialGroup()
                        .addGroup(dlgProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcodprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lbl1))
                        .addGap(11, 11, 11)
                        .addGroup(dlgProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(14, 14, 14)
                        .addGroup(dlgProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dlgProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCostoprod, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(8, 8, 8)
                        .addGroup(dlgProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPrecioprod, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(dlgProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(CbCategoriaprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(dlgProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAceptarprod, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelarprod, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(dlgProductoLayout.createSequentialGroup()
                        .addComponent(lblimagenprod, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExaminar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblproducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Descirpcion", "Costo", "Precio", "Categoria", "Imagen"
            }
        ));
        jScrollPane1.setViewportView(tblproducto);

        lblmensajes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblmensajes.setText(" Sistema Producto 1.0");

        jLabel1.setText("Buscar");

        btnnuevoprod.setText("Nuevo");

        btneditarProd.setText("Editar");

        btneliminarProd.setText("Eliminar");

        btnimprimirProd.setText("Imprimir");

        btnactualizarProd.setText("Actualizar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(txtbuscarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnnuevoprod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btneditarProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btneliminarProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnactualizarProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnimprimirProd)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnimprimirProd, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtbuscarProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(btnnuevoprod)
                        .addComponent(btneditarProd)
                        .addComponent(btneliminarProd)
                        .addComponent(btnactualizarProd)))
                .addContainerGap())
        );

        btnCerrarJFProd.setText("Cerrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblmensajes, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrarJFProd)
                .addContainerGap(21, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmensajes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrarJFProd)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTextArea getTfdescripcionprod() {
        return tfdescripcionprod;
    }

    public void setTfdescripcionprod(JTextArea tfdescripcionprod) {
        this.tfdescripcionprod = tfdescripcionprod;
    }

    public JComboBox<String> getCbCategoriaprod() {
        return CbCategoriaprod;
    }

    public void setCbCategoriaprod(JComboBox<String> CbCategoriaprod) {
        this.CbCategoriaprod = CbCategoriaprod;
    }

    public JButton getBtnAceptarprod() {
        return btnAceptarprod;
    }

    public void setBtnAceptarprod(JButton btnAceptarprod) {
        this.btnAceptarprod = btnAceptarprod;
    }

    public JButton getBtnCancelarprod() {
        return btnCancelarprod;
    }

    public void setBtnCancelarprod(JButton btnCancelarprod) {
        this.btnCancelarprod = btnCancelarprod;
    }

    public JButton getBtnExaminar() {
        return btnExaminar;
    }

    public void setBtnExaminar(JButton btnExaminar) {
        this.btnExaminar = btnExaminar;
    }

    public JDialog getDlgProducto() {
        return dlgProducto;
    }

    public void setDlgProducto(JDialog dlgProducto) {
        this.dlgProducto = dlgProducto;
    }

    public JLabel getLblimagenprod() {
        return lblimagenprod;
    }

    public void setLblimagenprod(JLabel lblimagenprod) {
        this.lblimagenprod = lblimagenprod;
    }

    public JLabel getLblmensajes() {
        return lblmensajes;
    }

    public void setLblmensajes(JLabel lblmensajes) {
        this.lblmensajes = lblmensajes;
    }

    public JTextField getTxtCostoprod() {
        return txtCostoprod;
    }

    public void setTxtCostoprod(JTextField txtCostoprod) {
        this.txtCostoprod = txtCostoprod;
    }

    public JTextField getTxtNombreprod() {
        return txtNombreprod;
    }

    public void setTxtNombreprod(JTextField txtNombreprod) {
        this.txtNombreprod = txtNombreprod;
    }

    public JTextField getTxtPrecioprod() {
        return txtPrecioprod;
    }

    public void setTxtPrecioprod(JTextField txtPrecioprod) {
        this.txtPrecioprod = txtPrecioprod;
    }

    public JTextField getTxtcodprod() {
        return txtcodprod;
    }

    public void setTxtcodprod(JTextField txtcodprod) {
        this.txtcodprod = txtcodprod;
    }

    public JButton getBtnCerrarJFProd() {
        return btnCerrarJFProd;
    }

    public void setBtnCerrarJFProd(JButton btnCerrarJFProd) {
        this.btnCerrarJFProd = btnCerrarJFProd;
    }

    public JButton getBtnactualizarProd() {
        return btnactualizarProd;
    }

    public void setBtnactualizarProd(JButton btnactualizarProd) {
        this.btnactualizarProd = btnactualizarProd;
    }

    public JButton getBtneditarProd() {
        return btneditarProd;
    }

    public void setBtneditarProd(JButton btneditarProd) {
        this.btneditarProd = btneditarProd;
    }

    public JButton getBtneliminarProd() {
        return btneliminarProd;
    }

    public void setBtneliminarProd(JButton btneliminarProd) {
        this.btneliminarProd = btneliminarProd;
    }

    public JButton getBtnimprimirProd() {
        return btnimprimirProd;
    }

    public void setBtnimprimirProd(JButton btnimprimirProd) {
        this.btnimprimirProd = btnimprimirProd;
    }

    public JButton getBtnnuevoprod() {
        return btnnuevoprod;
    }

    public void setBtnnuevoprod(JButton btnnuevoprod) {
        this.btnnuevoprod = btnnuevoprod;
    }

    public JTable getTblproducto() {
        return tblproducto;
    }

    public void setTblproducto(JTable tblproducto) {
        this.tblproducto = tblproducto;
    }

    public JTextField getTxtbuscarProd() {
        return txtbuscarProd;
    }

    public void setTxtbuscarProd(JTextField txtbuscarProd) {
        this.txtbuscarProd = txtbuscarProd;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbCategoriaprod;
    private javax.swing.JLabel Lbl1;
    private javax.swing.JButton btnAceptarprod;
    private javax.swing.JButton btnCancelarprod;
    private javax.swing.JButton btnCerrarJFProd;
    private javax.swing.JButton btnExaminar;
    private javax.swing.JButton btnactualizarProd;
    private javax.swing.JButton btneditarProd;
    private javax.swing.JButton btneliminarProd;
    private javax.swing.JButton btnimprimirProd;
    private javax.swing.JButton btnnuevoprod;
    private javax.swing.JDialog dlgProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblimagenprod;
    private javax.swing.JLabel lblmensajes;
    private javax.swing.JTable tblproducto;
    private javax.swing.JTextArea tfdescripcionprod;
    private javax.swing.JTextField txtCostoprod;
    private javax.swing.JTextField txtNombreprod;
    private javax.swing.JTextField txtPrecioprod;
    private javax.swing.JTextField txtbuscarProd;
    private javax.swing.JTextField txtcodprod;
    // End of variables declaration//GEN-END:variables
}
